# These are the standard defaults from new_project_template
application: your_app_identifier
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static resources
# This will avoid a few warnings in your App Engine dashboard
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: optional

# We'll use this to serve the video
- url: /static
  static_dir: static
  secure: optional

# Dynamic handlers (including Glass subscriptions)
# Notice we force a secure connection, otherwise they won't work
- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: "0.15"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
